# Generated by Django 5.2.8 on 2025-11-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodations',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=100)),
            ],
        ),
    ]
