# Generated by Django 5.2.8 on 2025-11-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('restaurant', 'Restaurant'), ('lodge', 'Lodge')], default='hotel', max_length=20),
        ),
    ]
