# Generated by Django 5.2.8 on 2025-11-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_accommodations_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='locations/images/'),
        ),
    ]
