# Generated by Django 5.2.8 on 2025-11-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_accommodations_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodations',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='locations/static/images/'),
        ),
    ]
